language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
install:
    - pip install -U -r requirements.txt --use-mirrors
before_success:
  - coverage erase
script:
    - nosetests --with-coverage --cover-package=changes
after_success:
  - coverage combine
  - coveralls
  - ocular
