language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
install:
  - pip install -U -r requirements.txt
before_success:
  - coverage erase
script:
  - py.test --durations=10 --cov changes --cov-report term-missing -x tests
after_success:
  - coverage combine
  - coveralls
  - ocular
